### ISSUE TITLE
distribution parameterization by keyword arguments

### ISSUE THREAD

**Issue by bertdv** [biaslab/ReactiveMP.jl#1]
This is not really a feature request but rather a discussion item that concerns distributions like  `NormalMeanVariance()`, `NormalMeanPrecision()` etc.
Rather than
```
xt_min ~ NormalMeanVariance(xt_min_mean, xt_min_var)
```
is there a reason why we dont write
```
xt_min ~ Normal( mean=xt_min_mean, var=xt_min_var)
```
This way you can also write
```
xt_min ~ Normal( natural_mean=xt_m, precision=xt_v)
```
You get the idea. The parameter list determines whether you have the moment or information parameterization scheme.

I think it's cleaner and more consistent with other notation. Eg, we dont write `GammaShapeScale` but just `Gamma` for the Gamma distribution and all the exponential family distributions have moment and canonical parameterizations, so the user would not know if you use `GammaShapeScale` or `GammaShapeRate`. Here, I would also recommend 
```
Gamma(shape= ..., scale= ...)
```
to make the chosen parameterization clear.

**Comment by bvdmitri** [comment]
Added in https://github.com/biaslab/GraphPPL.jl/pull/18
