### ISSUE TITLE
MethodError: no method matching keys(::KeepLast)

### ISSUE THREAD

**Issue by wmkouw** [biaslab/ReactiveMP.jl#115]
This error might occur while using the automatic inference block. For example:

```
result = inference(
    model         = Model(model), 
    data          = (y = 0.3,),
    returnvars    = (x = KeepLast())
)
```

Julia: 1.7.2
```
  [b3f8163a] GraphPPL v2.0.1
  [bdcacae8] LoopVectorization v0.12.108
  [92933f4c] ProgressMeter v1.7.2
  [a194aa59] ReactiveMP v2.0.1
  [df971d30] Rocket v1.3.20
```

**Comment by wmkouw** [comment]
The keyword arguments expect Tuples. Fix: add a comma -> `(x = KeepLast(),)`.

**Comment by bvdmitri** [comment]
We should add a simple check if input either is a `Tuple` or a `Dict` and display some readable error message otherwise.
