### ISSUE TITLE
Add the possibility of blocking updates of the initialized marginals.

### ISSUE THREAD

**Issue by albertpod** [biaslab/ReactiveMP.jl#12]
When running variational message passing, `ReactiveMP.jl` updates all random variables.
For prototyping/experimenting, it is sometimes useful to block some of the marginal updates.
For now, I see only one way of enforcing this behavior by substituting `randomvar` with `datavar`.
This is option is undesirable as it requires some changes in model/inference specification.

**Comment by bvdmitri** [comment]
Should be fixed by #69

**Comment by albertpod** [comment]
Sure not #70?

**Comment by bvdmitri** [comment]
Yeah, you are right @albertpod. We can close this issue then.
