### ISSUE TITLE
Support of message passing for Boolean functions

### ISSUE THREAD

**Issue by albertpod** [biaslab/ReactiveMP.jl#120]
Currently, `ReactiveMP.jl` does not support inference in Belief networks composed of Bernoulli random variables (RVs).

One good example of such a network is shown in [Chapter 2](https://www.mbmlbook.com/LearningSkills.html) of Bishop's **Model-Based Machine Learning** book.

The dependencies between these variables are enforced by logic functions, e.g., `AND`, `NOT`, `OR`, etc.

`ForneyLab.jl `has the demo on [building `AND` node](https://github.com/biaslab/ForneyLab.jl/blob/master/demo/implementing_additional_nodes.ipynb). 

A related [issue](https://github.com/biaslab/ForneyLab.jl/issues/200) was initially opened in `ForneyLab.jl`.

**Comment by bvdmitri** [comment]
Fixed in #170
