### ISSUE TITLE
average energy computation for the Wishart node

### ISSUE THREAD

**Issue by albertpod** [biaslab/ReactiveMP.jl#148]
I've been looking into the computation of average energy for the `Inverse-Wishart `node.
So I had a look at the computation of this quantity for `Wishart` node as well.
It appears to me that the average energy computation for the `Wishart` node is incorrect, i.e.,

`@average_energy Wishart (q_out::Any, q_ν::Any, q_S::Any)`

You would normally expect `q_out` to be Wishart distribution, meaning that we'd need to take the log expectation of `q_out`, not just `logdet(m_q_out)` where `m_q_out = mean(q_out)`. 

It seems to me that [ForneyLab.jl ](https://github.com/biaslab/ForneyLab.jl/blob/fca07c3bcb3a5abe7393dfb275a2e47e54fd68aa/src/factor_nodes/wishart.jl#L137)does it properly. Is there something I miss?

**Comment by bartvanerp** [comment]
I think you might be right. Previously (before @bvdmitri introduced the `mean(logdet, x)` syntax) this also was incorrect for the `Gamma` node. It seems that we overlooked this one.

**Comment by albertpod** [comment]
I guess we are missing the `mean(inverse, x) `function for some distributions.

**Comment by bvdmitri** [comment]
Indeed it looks like an artefact of the old confusion between `unsafeDetLogMean(...)` and `logdet(mean(...))`, which was wrong. We replaced `logdet(mean())` with `mean(logdet, ...)` but overlooked this one. Thanks @albertpod !

**Comment by bvdmitri** [comment]
Fixed with #149 . Thanks @albertpod !
