### ISSUE TITLE
Implement RequireInboundMarginal

### ISSUE THREAD

**Issue by bvdmitri** [biaslab/ReactiveMP.jl#151]
In the same way as we have `RequireInbound` for messages we may want to add `RequireInboundMarginal` or smth similar to request marginals on inbound edges for further messages computation.

**Comment by albertpod** [comment]
I agree it's an interesting idea. I would like to see the motivation for this scenario, however.

**Comment by bvdmitri** [comment]
@albertpod I suppose EFE optimisation messages might require it. I got this feature request from @MagnusKoudahl initially

**Comment by bertdv** [comment]
this comment may not be relevant since I dont know the context, but in general it makes sense to me to add this feature. After all, computation of the marginal is really computation of an outgoing message of an `equality node` that has been inserted at the location of the marginal.

**Comment by MagnusKoudahl** [comment]
@bvdmitri For GFE messages, marginals are updated based on a different functional, so we are looking for different marginals than we would with VMP/BP. So in a sense, it's not too surprising that the equations end up looking different and require a slightly different set of intuitions

**Comment by bvdmitri** [comment]
Added in #160
