### ISSUE TITLE
Updating parameters

### ISSUE THREAD

**Issue by Sepideh-Adamiat** [biaslab/ReactiveMP.jl#166]
I was trying to update a parameter and I faced this error:

`
x = datavar(PointMass{Float64}, ...)' accepts data of type PointMass{Float64}, but Irrational{:π} has been supplied. Check 'update!(x, data::Irrational{:π})' and explicitly convert data to type PointMass{Float64}.`

This is how I updated the x parameter with the goal:
`goal = [π for t in 1:T]`
`(x, x_0, z, znodes, u, zcm, zcc) = model.model_variables`
`update!(x, goal)`

And this is my model:

```julia
@model function pendulum_controller(T, A, B, Q, C, R, m_u, v_u)

    cA = constvar(A) # Transition matrix
    cB = constvar(B) # Control matrix
    cC = constvar(C) # Observation matrix
    cQ = constvar(Q) # Process noise covariance matrix
    cR = constvar(R) # Measurement noise covariance matrix
    
    # Vector of reference to factor nodes of latent states
    znodes = Vector{FactorNode}(undef, T)
    
    z = randomvar(T)        # Hidden states
    u = randomvar(T)        # Controls
    x = datavar(Float64, T) # Goal observations

    # Parameters of prior state
    zcm = datavar(Vector{Float64})
    zcc  = datavar(Matrix{Float64})
    
    # Prior state
    z_prior ~ MvNormalMeanCovariance(zcm, zcc)
    z_prev = z_prior
    
    # Current observation for filtering
    x_0 = datavar(Float64)
    x_0 ~ NormalMeanVariance(dot(cC, z_prior), cR)

    # Extend the model T steps into the future
    for t in 1:T
        
        # Control prior at t
        u[t] ~ NormalMeanVariance(m_u, v_u)
        
        # State transition at t
        znodes[t], z[t] ~ MvNormalMeanCovariance(cA * z_prev + cB * u[t], cQ)
        
        # Likelihood at t
        x[t] ~ NormalMeanVariance(dot(cC, z[t]), cR)
        
        # Update previous state
        z_prev = z[t]
    end

    return x, x_0, z, znodes, u, zcm, zcc
end 
```

**Comment by bvdmitri** [comment]
That is an interesting one. This comes from the fact that 

```julia
typeof(π) !== Float64 # yeap, π has its own separate type actually
```

So when `datavar(Float64)` expects `Float64` it is impossible to pass `π`. An easy fix would be to:

```julia
update!(x, convert(Float64, π))
```

We probably can always call `convert(Float64, input)` inside `update!` function. What do you think guys @albertpod @bartvanerp

**Comment by bauglir** [comment]
Note that `π` is an `Irrational`, which also applies to `ℯ` and probably some other constants. Perhaps an adding an explicit method for `Irrational{S}` to `update!` is an alternative to always calling `convert`?

**Comment by bartvanerp** [comment]
Bit late to the discussion, but indeed implementing some error message when there is a discrepancy between datavar type and data type might be the best solution.

**Comment by bvdmitri** [comment]
Error message improved in #167
