### ISSUE TITLE
Error reporting for Progress in automatic inference API

### ISSUE THREAD

**Issue by wmkouw** [biaslab/ReactiveMP.jl#192]
In `inference(model=, ...)`, setting `showprogress=true` for a model that defaults to sum-product message passing will generate:
```
MethodError: no method matching Progress(::Nothing)
```
I first thought that I had forgotten to import ProgressMeter. I only realized later on that the model was silently defaulting to sum-product (it was previously using VMP and I made a small alteration to the model specification), in which, of course, no iteration occurs (and measuring progress doesn't make sense).

Generating a more descriptive error message might seem unnecessary, but I think it would help improve user experience. It's a small fix. I'll leave this open a few days in case someone wants to pick it up as their first issue. If not, I'll add it next week.

MWE:
```
@model function mwe()
    
    x = datavar(Float64)
    
    # Prior mean
    μ ~ NormalMeanVariance(0,1)
    
    # Likelihood
    x ~ NormalMeanVariance(μ,1)
    
    return x,μ
end

result = inference(
    model = Model(mwe),
    data = (x = 1.0,),
    returnvars = (μ = KeepLast(),),
    showprogress = true,
)
```

Versions:
- Julia: 1.7.2
- ReactiveMP: 2.4.1

**Comment by wmkouw** [comment]
Come to think of it, perhaps a `verbose` flag where `inference()` reports details would be useful as well. What do you think?

**Comment by bvdmitri** [comment]
That is a great catch @wmkouw . I think I accidentally broke this in #178 . 
The fix should be easy, in the `inference.jl` file line `412` must be moved to after line `427` as it tries to create a progress meter before iterations were defined properly.

**Comment by wmkouw** [comment]
Note that `ProgressMeter.Progress(iterations)` in `412` must also be changed to `ProgressMeter.Progress(_iterations)`.
