### ISSUE TITLE
Wishart marginal not Hermitian in static model

### ISSUE THREAD

**Issue by wmkouw** [biaslab/ReactiveMP.jl#193]
Inference of a precision matrix in a static model produces a non-Hermitian Wishart marginal and a subsequent non-positive definite error when converting to PDMat object:
```
PosDefException: matrix is not positive definite; Cholesky factorization failed.
```

An example of the posterior scale matrix parameter before casting to PDMat is:
```
S = [-1.407 0.0599; -0.055 0.0023]
```
which is clearly not symmetric.

Example MWE:
```
# Sample size
N = 100

# True covariance matrix
Σ_true = [1.0 0.1;0.1 1.0]

# Generate data
X = randn(N,2)*cholesky(Σ_true).U

@model function modelΛ(N)
    
    X = datavar(Vector{Float64}, N)
    
    # Precision prior
    Λ ~ Wishart(3, diageye(2))
    
    # Likelihood
    for i in 1:N
        X[i] ~ MvNormalMeanPrecision(zeros(2), Λ)
    end
    
    return X, Λ
end

results = inference(
    model = Model(modelΛ, N),
    data = (X = [X[i,:] for i = 1:N],),
    returnvars = (Λ = KeepLast(),),
)

qΛ = results.posteriors[:Λ]
Σ_hat = inv(mean(qΛ))
```

We typically use the Wishart node to estimate process noise in dynamic model. In a static model, the problem does not occur at `N=1`, but starts to happen roughly 30% of the time at `N=10`, 50% at `N=20` and 100% at `N=100`. 

I suppose this is either a numerical instability that compounds over likelihood multiplications, or an error in the likelihood-based message from the`MvNormalMeanPrecision` node. Anyone else noticed this as well?

Versions:
- Julia: 1.7.2
- ReactiveMP: 2.4.1
- GraphPPL: 2.3.1

**Comment by wmkouw** [comment]
This has been found to be a tricky issue: the sum-product Wishart message is a special case of the variational message whose scale matrix is computed as `cholinv(v_mean + v_out + (m_mean - m_out) * (m_mean - m_out)')`). When the Gaussian likelihood's `out` and `mean` variables are known, i.e., of `PointMass` type, they have zero variance. The above calculation will default to `cholinv((m_mean - m_out) * (m_mean - m_out)')`, which is an inverse of a rank-1 matrix. `cholinv` will attempt a Cholesky factorization before inverting which fails and generates the `PosDefException` described above.

This is an inherent problem with message-passing since the messages are all based on local computations. If we were to look at all `N` samples in the model above, then the joint likelihood message above would be `cholinv(sum((m_mean - m_out) * (m_mean - m_out)'))`, which is non-singular when `N >= D`. We are currently thinking of `meta` solutions, such as delaying the inverse until the marginal calculation. But this isn't trivial.

Note that the marginal calculation based on the sum-product WishartMessage differs from the calculation on [Wikipedia](https://en.wikipedia.org/wiki/Conjugate_prior): that one is silently based on an InverseWishart likelihood.

**Comment by bvdmitri** [comment]
@wmkouw Please review #196 . This PR changes `WishartMessage` structure such that it stores inverse of the scale matrix, so we do not need to take an inverse of rank-1 matrix. `prod` also becomes easier (just a simple summation) with this change. The only one downside is that it will no longer be possible to make an improper Wishart prior (e.g. with zeroed scale matrix), but IMO it is a fair limitation.
