### ISSUE TITLE
Support `::Function` in the `PointMass` and `constvar` constructor.

### ISSUE THREAD

**Issue by bvdmitri** [biaslab/ReactiveMP.jl#202]
@ismailsenoz noticed, that `ReactiveMP.jl` fails if some attempts to pass a `::Function` object to an interface of some node. The problem is in the https://github.com/biaslab/ReactiveMP.jl/blob/b00efa9a5ca42250a21eef8c46d9fead5e1c3ac1/src/variables/constant.jl#L45 method which assumes that this function is supposed to generate a constant value, but this is not true. This method should be relaxed to accept at leas one `::Int` (instead of `::Vararg{Int}` which also dispatches on cases where no `dims` is present).

**Comment by HoangMHNguyen** [comment]
I checked the `constvar` with `::Function` and saw that `constvar` would return an array of  `ConstVariable`. So what I did was I added another method for `constvar` with `::Function` so that it returns the function as a `ConstVariable`.

**Comment by albertpod** [comment]
I see a PR associated with this issue, but there is no follow-up. @HoangMHNguyen please update the status of the issue and PR.

**Comment by bvdmitri** [comment]
@albertpod I forgot about it, my bad. I’ll try to finish this week
