### ISSUE TITLE
Discuss default `meta::Any` dispatch specification in the `@rule` macro

### ISSUE THREAD

**Issue by bvdmitri** [biaslab/ReactiveMP.jl#205]
Currently, `ReactiveMP.jl` implicitly sets `meta::Any` in the generated by the `@rule` macro message update rule code if no `meta::SomeOtherType` has been specified explicitly. For example, the rule:
```
@rule NormalMeanVariance(:out, Marginalisation) (q_μ::Any, q_v::Any) = NormalMeanVariance(mean(q_μ), mean(q_v))
```
implictly sets `meta::Any`. This is an implementation detail, but it has some consequences for users as well. I will refer to `meta::Any` rule as to a "default" rule.

- A user can specify a meta object and an associated rule only for one edge, `ReactiveMP.jl` will use the "default" rules for remaining edges
- A user might make a mistake in their rule specification and `ReactiveMP.jl` will silently pick the "default" rules for all edges.
- `ReactiveMP.jl` always picks the "default" rule and never errors if:
    - User specified meta in the model specification, e.g. `y ~ NormalMeanVariance(x, z) where { meta = MyCustomMeta() }`
    - No rules for `MyCustomMeta` exist

Bullet 1 is sort of a feature, which allows user to quickly change rules for only one edge. Bullets 2 and 3, however, may be non intuitive. The current behaviour must be either documented explicitly or we should change the default rule specification to `meta::Nothing`, such that "rule not found" error pops up in these cases. I opened this issue such that we discuss and deliberately close it with some decision.

**Comment by bartvanerp** [comment]
This seems like quite a crucial topic indeed. The second bullet that you post can occur quite easily, and requires quite some advanced knowledge to fix (I did not know about this and my solution would likely be to add print statements in the rules). Therefore, I think that having `meta::Nothing` as a default makes the most sense to select the default message passing rules. The user can then use the custom `meta` object to deviate from these rules. Errors that then might popup, such as missing rules, do suddenly make sense as the user explicitly wants to deviate from the standard rules.
I am not sure about the consequences/downsides for `meta::Nothing`, but it seems like the most Julia-ish solution.

**Comment by MagnusKoudahl** [comment]
I agree with @bartvanerp . While the option to quickly experiment with rules on single edges is useful, in my experience it's very low overhead (if a bit tedious) to define rules for a custom `meta` that just call existing rules. I'd also argue that changing rules on single edges for existing nodes is a niche enough scenario that it makes more sense to prevent an easy footgun. 
For those reasons, I'd say that having a default `nothing` meta is a good way to go

**Comment by bvdmitri** [comment]
I agree with both of you and also wanted to change the default specification from `Any` to `Nothing`, but decided to open a discussion. The PR is ready, we can wait if someone has an objection and if not then we can merge.
