### ISSUE TITLE
Add soft dot product

### ISSUE THREAD

**Issue by albertpod** [biaslab/ReactiveMP.jl#231]
Currently, `ReactiveMP.jl` does not support the dot product of two Gaussians.
Essentially the variational update rules for such a node are a particular case of the existing AR node, the difference is in the absence of a buffering procedure for the soft product node.

Usage example:
```julia
@model function (args)
    x ~ MvNormal(...)
    z ~ MvNormal(...)
    p ~ Gamma(...)
    y ~ Normal(dot(x, z), p)
end
```

**Comment by abpolym** [comment]
Updating my self-imposed deadline as it was a wildly optimistic estimate.

To get a better estimate, I'll experiment with the trivariate analysis in the `Clean Coder` book in this issue:

* `O` optimistic estimate
* `N` nominal estimate
* `P` pessimistic estimate

For this issue I estimate`(O,N,P) = (5,14,31)` which yields `μ = (O+4N+P)/6 = 15.33` and `σ = (p-o)/6 = 4.33` yielding a probability distribution for the task (completed) `N(μ = 15.33, σ = 4.33)`.
To get a deadline, I'll just add the mean: `deadline = today + μ = 24.11.2022`.

**Comment by albertpod** [comment]
It seems like we are running out of the pessimistic estimate. @abpolym do you need help with that?

**Comment by abpolym** [comment]
New trivariate analysis:

Decreased `P` significantly: After spending more time on the material I got more certain about it.
Increased `O`: This task is currently not my top priority, but I am still spending time on it every week (~some hours for 1-2 days a week).

`(O,N,P) = (12,19,14)` resulting in `μ = (O+4N+P)/6 = 17.00` and `σ = (P-O)/6 = 0.33` which yields a new deadline: `22.02.2022`.

**Comment by albertpod** [comment]
Please update the end date of this project ;)
