### ISSUE TITLE
Ambiguity with `probvec` for `Bernoulli` distribution

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/ReactiveMP.jl#255]
Not sure whether this is an issue, but I think it might be good to discuss this.

Consider `z = Categorical([0.1, 0.2, 0.7])`, which has classes `{1, 2, 3}`. If we call `probvec` on this distribution, we obtain `probvec(z) = [0.1, 0.2, 0.7]`, where the elements are nicely ordered according to the classes.

Now consider `y = Bernoulli(0.6)`, with classes `{0, 1}`. If we call `probvec` on this distribution, we obtain `probvec(y) = [0.6, 0.4]`. However, these correspond to the classes `1` and `0`, respectively. This ordering is different compared to the categorical one, although in this case we are ofc working with binary values.

This might cause some confusion and as a result some bugs might sneak in.

**Comment by bvdmitri** [comment]
I agree the current behaviour is odd, but also looks like something that can easily be fixed/improved.

**Comment by bartvanerp** [comment]
Incorrect behaviour here: 
https://github.com/biaslab/ReactiveMP.jl/blob/b60f3f1d48e2383274ea78f153be5d9743f73f45/src/distributions/bernoulli.jl#L25-L28
