### ISSUE TITLE
Revision of approximations

### ISSUE THREAD

**Issue by albertpod** [biaslab/ReactiveMP.jl#276]
The issue at hand pertains to the `ReactiveMP.jl `folder named `approximations/`, which is growing and being poorly maintained.
In essence, approximation methods should not be included in message-passing since they are semantically distinct entities.
The proposed solution is to enhance and relocate the `approximation/ `folder within `ExpectationApproximations.jl`

**Comment by bartvanerp** [comment]
Is this a duplicate of #27?
