### ISSUE TITLE
Folder structures in `src` and `test` do not fully align

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/ReactiveMP.jl#287]
e.g. the `test` folder contains an `algebra` folder, which does not appear in the same location as in the `src` folder. Perhaps there are more cases. Perhaps we can add tests for this?

**Comment by bvdmitri** [comment]
Perhaps an artifact from refactoring part of the code from ReactiveMP to RxInfer. We should fix it .

**Comment by bvdmitri** [comment]
@abpolym You were assigned. This task has been added to the [milestone](https://github.com/biaslab/RxInfer.jl/milestone/1) for tracking and prioritization.

**Comment by abpolym** [comment]
I can check it out after next week Wednesday. Should be an easy fix, though

**Comment by bvdmitri** [comment]
@abpolym 
This task has been added to the [milestone](https://github.com/biaslab/RxInfer.jl/milestone/2) for tracking and prioritization.
