### ISSUE TITLE
The documentation needs "how to add nodes and rules"

### ISSUE THREAD

**Issue by albertpod** [biaslab/ReactiveMP.jl#296]
Neither `RxInfer.jl `nor `ReactiveMP.jl` instructs the [users](https://discourse.julialang.org/t/problems-fitting-a-simple-multinomial-model-in-rxinfer/95442) on how to implement missing nodes and rules (BP, VMP, EP).

We should definitely include the recipe in the documentation.

**Comment by bvdmitri** [comment]
This should also include the explanation of how to write rule that may return both `Univariate` and `Multivariate` outputs.

**Comment by albertpod** [comment]
Closed: ref https://github.com/biaslab/RxInfer.jl/pull/105
