### ISSUE TITLE
Missing rules `Multiplication` and `Addition` node

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/ReactiveMP.jl#311]
The `Multiplication` node misses some rules, which harm the user-friendliness.
These rules include (but might not be limited to)
```julia
(*)(::PointMass{<:Real}, ::MultivariateNormalDistributionsFamily)
(*)(::PointMass{<:UniformScaling}, ::MultivariateNormalDistributionsFamily)
```

**Comment by bartvanerp** [comment]
Also add
```julia
@rule typeof(+)(:in1, ReactiveMP.Marginalisation) (m_out::Missing, m_in2::PointMass) = m_out

@rule typeof(+)(:in1, ReactiveMP.Marginalisation) (m_out::Missing, m_in2::MvNormalMeanCovariance, ) = m_out

@rule typeof(*)(:in, ReactiveMP.Marginalisation) (m_out::Missing, m_A::PointMass, meta::ReactiveMP.TinyCorrection) = m_out
```

**Comment by bvdmitri** [comment]
I'm a bit hesitant to add rules with `Missing` as an argument, because technically it is still a hacky way to pass empty observations and many other parts in `ReactiveMP` still do not play well with `Missings` (e.g. joint-marginals, average energy and entropies).

**Comment by bvdmitri** [comment]
#248 adds rules with missings, do we still need the others?

**Comment by bartvanerp** [comment]
I think they would still be nice to have
