### ISSUE TITLE
Add special treatment for the Uniform node

### ISSUE THREAD

**Issue by albertpod** [biaslab/ReactiveMP.jl#341]
Unifrom node won't be a part for ExponentialFamily.jl, however it's an important distribution in statistical inference that has many cool properties.

I suggest we extend Uniform node by "marrying" it with any other node representing distributions from exponential family.

For example, if Uniform distribution acts as a prior for Poisson we can approximate the outgoing message by transforming Uniform distribution into the distribution of the same form as incoming message. Preferrably, the incoming message  corresponds to a distribution that has known CDF and inverse CDF, but of course its not a limiting factor. Once the transformation is done, we can compute the marginal posterior on the edge and then the inference will run fast. Similar to what we've done with HalfNormal node, but the generalization of this for Uniform node would be cool imho.

P.S. Perhaps Poisson is not the best example as the resulting product is not Poisson anymore :)

**Comment by bvdmitri** [comment]
> by transforming Uniform distribution into the distribution of the same form as incoming message

> Once the transformation is done, we can compute the marginal posterior

As discussed in person, I'm very skeptical about this. IMO there is no need to approximate/transform the Uniform distribution into anything. Computing the posterior with Uniform is super easy and straightforward and does not require any sort of transformation. Basically the product with Uniform gives you a truncated version of what you had before. 

The Uniform distribution acts as a constraint on your support. We cannot really give up this knowledge and pretend we approximate the uniform as a Gaussian and return the posterior in the Gaussian form. Well we can, but I'm skeptical this is the right way to do it. 

This being sad, we must be able to work with the Uniform distribution, but I think the right way to go is to implement rules/products with generic truncated distributions. Then uniform will work automatically.
