### ISSUE TITLE
n_samples argument is not used in CVI

### ISSUE THREAD

**Issue by bvdmitri** [biaslab/ReactiveMP.jl#358]
The second argument `n_samples` is not used in the CVI algorithm. It is confusing, it either should be removed or it can be a bug.

**Comment by Nimrais** [comment]
It will be removed

**Comment by Nimrais** [comment]
Oh stop, not in ReactiveMP it's needed. It's controlling number of samples, that will send for forward message.

**Comment by Nimrais** [comment]
Look here https://github.com/biaslab/ReactiveMP.jl/blob/main/src/rules/delta/cvi/out.jl
