### ISSUE TITLE
A model with switching dynamics silently yields an empty buffer

### ISSUE THREAD

**Issue by Sibgatulin** [biaslab/ReactiveMP.jl#36]
Hey everyone!

Thanks for the work put in ReactiveMP and the surrounding projects, it looks very interesting!

This is, perhaps, more of a question than an issue, so please feel free to redirect it to a more suitable platform, if any.

I've been trying to build a form of a Switching Linear Dynamical System (SLDS), which has the transition of a continuous latent variable (``x``) conditioned on the value of a categorical latent variable (``s``). Attached DAG attempts to illustrates it (note that I am using a continuous auxiliary variable ``α`` to condition ``x``). 

The complete attempt with some details can be found in [this notebook](https://github.com/Sibgatulin/LearningBayes.jl/blob/main/notebooks/switching_linear_dynamics-mwe.ipynb), but in the very nutshell:
- I am trying to use ``Transition`` to condition ``α`` on ``s`` (much like the emitted value ``y`` in your HMM demo)
```julia
    α ~ Transition(s[t], Tα) # typeof(Tx) == MatrixDirichlet{Float64, Matrix{Float64}}
```
- then I construct a node ``Tx`` to compute µ for the next ``x``
```julia
    Tx ~ 1 + (-dt) * α # typeof(dt) == Float64
    x[t] ~ NormalMeanVariance(Tx * x_prev, σx) 
```
My most naive implementation of the inference silently returns empty buffers and I am clueless how to debug it. The notebook includes a working, slightly simpler form of the model without the latent ``s``, and this is the only reason I assume I am misusing ``α ~ Transition`` or node generation for ``Tx``... Please, let me know if there is a piece of documentation I am missing. 

![dag-1](https://user-images.githubusercontent.com/10868826/129347899-8813d905-8c3a-4e6f-ba80-9b5bfdd0d7f5.png)

**Comment by bvdmitri** [comment]
Hey @Sibgatulin! Thanks for trying out ReactiveMP:

In your model with extra factorisation constraint  `where { q = q(out, in)q(a) }` around Transition node means that you are doing Variational Message Passing, and usually for VMP it is important to set initial marginals to start iterating from. Here I slightly modified your example (I also used a mean-field assumption around `α` Transition node `where { q = q(out)q(in)q(a) }`):

```Julia
@model function model_via_transition(n, μ0, dt, σx::ConstVariable, σy::ConstVariable)
    
    s  = randomvar(n) # discrete state variable
    α  = randomvar(n)
    
    x = randomvar(n) # continuous latent variable
    y = datavar(Float64, n)
    
    s_prior ~ Categorical(fill(1.0 / 2.0, 2))
    x_prior ~ NormalMeanVariance(μ0, σx)
    
    Ts ~ MatrixDirichlet([8. 2.; 2. 8.]) # arbitrary (and ideally learnable) transition matrix for the discrete state
    Tα ~ MatrixDirichlet([α0 0; 0 α1]) # auxilary "transition matrix" for switching decay rate parameter
    
    s_prev = s_prior
    x_prev = x_prior
    
    mindt = constvar(-dt)
    
    for t in 1:n
        s[t] ~ Transition(s_prev, Ts) where { q = q(out, in)q(a) }
        α[t] ~ Transition(s[t], Tα) where { q = q(out)q(in)q(a) }
        Tx ~ 1 + mindt * α[t]
        x[t] ~ NormalMeanVariance(Tx * x_prev, σx)
        y[t] ~ NormalMeanVariance(x[t], σy)
        
        s_prev = s[t]
        x_prev = x[t]
    end
    
    return s, α, x, y, Ts, Tα, s_prior, x_prior
end
```

And the inference procedure becomes:

```Julia
function inference(model_func, observations, vmp_iter, dt, μ0, σx, σy)
    n = length(observations)

    model, (s, α, x, y, Ts, Tα, s_prior, x_prior) = model_func(n, μ0, dt, σx, σy);
    
    buffer_s = keep(Vector{Marginal})
    buffer_x = keep(Vector{Marginal})
    
    subs_s = subscribe!(getmarginals(s), buffer_s)
    subs_x = subscribe!(getmarginals(x), buffer_x)
    
    setmarginal!(s_prior, Categorical(fill(1.0 / 2.0, 2)))
    setmarginal!(x_prior, NormalMeanVariance(μ0, σx))
    
    setmarginals!(s, vague(Categorical, 2))
    setmarginals!(α, vague(Categorical, 2))
    
    setmarginal!(Ts, MatrixDirichlet([8. 2.; 2. 8.])) # possible to use vague as well
    setmarginal!(Tα, MatrixDirichlet([α0 0; 0 α1]))
    
    for i in 1:vmp_iter
        update!(y, observations)
    end
    
    unsubscribe!(subs_s)
    unsubscribe!(subs_x)
    
    return buffer_s, buffer_x
end
```

However this doesn't solve all of the issues because in this model there are some non-conjugate relationships between variables. Transition node returns `Categorical` distributions that later on connected to a multiplication in `(-dt) * Categorical(...)`. Currently `ReactiveMP` is not able to run inference for non-conjugate models. We are working on this issue.

**Comment by Sibgatulin** [comment]
Hi @bvdmitri! Thanks a lot for the quick and informative response. 
Admittedly, my decision to place the factorisation constraint was a little north of guessing ;) I also realised now that I glanced over the non-conjugacy issue. Thanks for the clarifications! 
In principle, the original issue of silently returning an empty buffer is also solved by your fixes, so I'll close this issue.
