### ISSUE TITLE
Variables connected to Uninformative node not inferred

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/ReactiveMP.jl#91]
I was working on creating a efficient Kalman filter in ReactiveMP and wanted to combine the equality and multiplication node are combined according to Table 4 in (Loeliger, 2007, The factor graph approach to model-based signal processing) as in  #73 . The message towards the future then corresponds to the new prior, etc.. In order to terminate the graph I used the `Uninformative` node to "close" the future. For efficiency it would here not suffice to put an uninformative normal prior on the future, as this would lead to unnecessary inversions.

Currently the `Uninformative` node is a `Deterministic` node. As a result, the variables connected to it are constant variables and are not inferred during inference.  In my case I call:
```julia
x ~ Uninformative()
y ~ Node(x)
```
so perhaps this particular ordering is something which causes the issues.

A fix would be to convert the `Uninformative` node to be a `Stochastic` node. By definition it should not influence the calculations in the rest of the model and therefore I propose to set its average energy to 0. However, this differs from the average energy of Normal priors with a very large variance:
https://github.com/biaslab/ReactiveMP.jl/blob/cee5ccd9d944c7746a9bc7e2a80b9e75bcfc9753/src/nodes/normal_mean_precision.jl#L15-L18
I think that it might be okay to set its average energy to 0 as it truly does not influence inference, contrary to the uninformative gaussian case where the zero mean could be propagated (informatively) using VMP.

**Comment by bvdmitri** [comment]
Bug confirmed. A bit more details about this:

GraphPPL treats expressions, e.g.
```
y ~ MvNormalMeanVariance(zeros(2), diageye(2))
```
like
```
tmp_y_mean ~ zeros(2)
tmp_y_diageye ~ diageye(2)
y ~ MvNormalMeanVariance(tmp_y_mean, tmp_y_diageye)
```
as there is no principled way to distinguish 

```
y ~ MvNormalMeanVariance(zeros(2), diageye(2))
```
and
```
y ~ MvNormalMeanVariance(f(args...), g(args...))
```

However, if all arguments to the `f` or `g` are known and constant ReactiveMP will ignore node creation and simply replace these expressions with `constvar`. `Uninformative` one is a tricky one though, it does not have any arguments. So ReactiveMP decides that all (empty) arguments are known and constant, which eventually triggers this bug. The workaround before this fix is merged is:

```
y = randomvar()
y ~ Uninformative()
```

Thanks @bartvanerp

**Comment by bvdmitri** [comment]
For later reference:
> I think that it might be okay to set its average energy to 0 as it truly does not influence inference
We should set `@average_energy` of `Uninformative` node to be equal to the `entropy(q_out)`, as any extra edge connection increases degree of a random variable here:

https://github.com/biaslab/ReactiveMP.jl/blob/cee5ccd9d944c7746a9bc7e2a80b9e75bcfc9753/src/score/variable.jl#L5-L10

With `@average_energy = entropy` extra degree should cancel out and will not influence BFE.

**Comment by bartvanerp** [comment]
Thanks, fixed in new commit.
